#!/bin/bash
set -e

# Stop and disable systemd service
if [ -d /run/systemd/system ]; then
    systemctl stop blackbox-server.service || true
    systemctl disable blackbox-server.service || true
fi

exit 0
